import { Timestamp } from "firebase/firestore";
import type { MA } from "@/types";

/**
 * Shown when the `mas` collection is empty so the directory still renders 10 cards.
 * TODO: Seed real `mas` documents in Firestore (Firebase Console or script).
 */
export const PLACEHOLDER_MAS: MA[] = [
  {
    id: "ma-01",
    name: "Alex Tan",
    department: "Marketing",
    joinYear: null,
    photoURL: "",
    bio: "TODO: Add bio in Firestore or edit as MA/Admin.",
    hasMemo: false,
    memoURL: null,
    memoUploadedAt: null,
    updatedAt: Timestamp.fromMillis(0),
    order: null,
    isPresenting: null,
    school: null,
    rotations: [],
  },
  {
    id: "ma-02",
    name: "Bernice Lim",
    department: "Product",
    joinYear: null,
    photoURL: "",
    bio: "TODO: Add bio in Firestore or edit as MA/Admin.",
    hasMemo: false,
    memoURL: null,
    memoUploadedAt: null,
    updatedAt: Timestamp.fromMillis(0),
    order: null,
    isPresenting: null,
    school: null,
    rotations: [],
  },
  {
    id: "ma-03",
    name: "Chris Ng",
    department: "Engineering",
    joinYear: null,
    photoURL: "",
    bio: "TODO: Add bio in Firestore or edit as MA/Admin.",
    hasMemo: false,
    memoURL: null,
    memoUploadedAt: null,
    updatedAt: Timestamp.fromMillis(0),
    order: null,
    isPresenting: null,
    school: null,
    rotations: [],
  },
  {
    id: "ma-04",
    name: "Dana Koh",
    department: "Operations",
    joinYear: null,
    photoURL: "",
    bio: "TODO: Add bio in Firestore or edit as MA/Admin.",
    hasMemo: false,
    memoURL: null,
    memoUploadedAt: null,
    updatedAt: Timestamp.fromMillis(0),
    order: null,
    isPresenting: null,
    school: null,
    rotations: [],
  },
  {
    id: "ma-05",
    name: "Ethan Wong",
    department: "Finance",
    joinYear: null,
    photoURL: "",
    bio: "TODO: Add bio in Firestore or edit as MA/Admin.",
    hasMemo: false,
    memoURL: null,
    memoUploadedAt: null,
    updatedAt: Timestamp.fromMillis(0),
    order: null,
    isPresenting: null,
    school: null,
    rotations: [],
  },
  {
    id: "ma-06",
    name: "Farah Rahman",
    department: "HR",
    joinYear: null,
    photoURL: "",
    bio: "TODO: Add bio in Firestore or edit as MA/Admin.",
    hasMemo: false,
    memoURL: null,
    memoUploadedAt: null,
    updatedAt: Timestamp.fromMillis(0),
    order: null,
    isPresenting: null,
    school: null,
    rotations: [],
  },
  {
    id: "ma-07",
    name: "Gavin Lee",
    department: "Legal",
    joinYear: null,
    photoURL: "",
    bio: "TODO: Add bio in Firestore or edit as MA/Admin.",
    hasMemo: false,
    memoURL: null,
    memoUploadedAt: null,
    updatedAt: Timestamp.fromMillis(0),
    order: null,
    isPresenting: null,
    school: null,
    rotations: [],
  },
  {
    id: "ma-08",
    name: "Hannah Chua",
    department: "Community",
    joinYear: null,
    photoURL: "",
    bio: "TODO: Add bio in Firestore or edit as MA/Admin.",
    hasMemo: false,
    memoURL: null,
    memoUploadedAt: null,
    updatedAt: Timestamp.fromMillis(0),
    order: null,
    isPresenting: null,
    school: null,
    rotations: [],
  },
  {
    id: "ma-09",
    name: "Irfan Hassan",
    department: "Esports",
    joinYear: null,
    photoURL: "",
    bio: "TODO: Add bio in Firestore or edit as MA/Admin.",
    hasMemo: false,
    memoURL: null,
    memoUploadedAt: null,
    updatedAt: Timestamp.fromMillis(0),
    order: null,
    isPresenting: null,
    school: null,
    rotations: [],
  },
  {
    id: "ma-10",
    name: "Jia Wei",
    department: "Strategy",
    joinYear: null,
    photoURL: "",
    bio: "TODO: Add bio in Firestore or edit as MA/Admin.",
    hasMemo: false,
    memoURL: null,
    memoUploadedAt: null,
    updatedAt: Timestamp.fromMillis(0),
    order: null,
    isPresenting: null,
    school: null,
    rotations: [],
  },
];

